# Generated by Django 2.2 on 2020-09-22 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='date',
            new_name='datetime',
        ),
    ]
